version: "3.8"

services:
  db:
    image: mysql:8.0.32
    restart: unless-stopped
    container_name: backend_ExclusiveAccess_259
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=exclusiveaccess
    ports:
      - 3307:3306
    volumes:
#      - ./db:/var/lib/postgresql/data
      - ./create-schema.sql:/docker-entrypoint-initdb.d/create-schema.sql
  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    ports:
      - 8081:8080
    environment:
      - spring.profiles.active=dev
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:mysql://db:3306/exclusiveaccess
      - spring.datasource.username=root
      - spring.datasource.password=password
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true